version: '3.1'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - /mnt/d/ContainersCFG/ELKConfig/kibana/config:/usr/share/kibana/config
    networks:
      - custom_net
networks:
  custom_net:
    name: custom_net
    external: true
